version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 18
    commands:
      - npm install -g aws-cdk
      - cd iac/cdk
      - npm update
      - cdk list  

  pre_build:
    commands:
      - echo Not implemented  yet
  build:
    commands:
      - echo Not implemented  yet
       #- cd iac/cdk
       #- echo 'Deploying the following Cloud formation stacks'
       #- cdk list -c environment=${ENVIRONMENT} -c region=${REGION}
       #- cdk deploy '*' --require-approval never -c environment=${ENVIRONMENT} -c region=${REGION} --toolkit-stack-name a206145-CdkToolkit